name = "create-combined-server"
author = "Propet"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b4e29197c6216e7d7c6ad1d85b212b1b49734d247a7ce218cd82d41521434c3f"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
